service: omni-ivia-updates

provider:
  name: aws
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  versionFunctions: false
  tags: ${self:custom.tags}
  stackTags: ${self:custom.tags}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
        - "ec2:CreateNetworkInterface"
        - "ec2:DescribeNetworkInterfaces"
        - "ec2:DeleteNetworkInterface"
        - "ec2:AssignPrivateIpAddresses"
        - "ec2:UnassignPrivateIpAddresses"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "sqs:GetQueueUrl"
        - "sqs:GetQueueAttributes"
        - "sqs:ReceiveMessage"
        - "sqs:DeleteMessage"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "sns:*"
      Resource: "*"
  runtime: nodejs18.x
  environment:
    REGION: ${self:custom.region}
    STAGE: ${self:custom.stage}
  deploymentBucket:
    name: ${ssm:/omni-dw/${self:provider.stage}/sls/deployment/bucket}
    serverSideEncryption: AES256

custom:
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  tags:
    Application: OmniRealTimeReplication
    CreateBy: BizCloudExperts
    Environment: ${self:custom.stage}

plugins:
  - serverless-offline
  - serverless-provisioned-concurrency-autoscaling
  - serverless-plugin-existing-s3

package:
  individually: true

layers:
  OmniIviaLayer:
    path: lambdaLayer/lib
    name: ${self:service}-layer-${self:provider.stage}
    description: Omni ivia lambda layer for all node modules - ${self:provider.stage}
    compatibleRuntimes:
      - nodejs14.x
    retain: false

functions:
  iviaSqsToDynamoDB: ${file(config/functions/iviaSqsToDynamoDB.yml):function}
  create-shipment: ${file(config/functions/create-shipment.yml):function}
  add-document-api: ${file(config/functions/add-document.yml):function}
  ivia-milhouse-movement-updates-query: ${file(config/functions/ivia-milhouse-movement-updates-query.yml):function}
  ivia-milhouse-movement-updates-processor: ${file(config/functions/ivia-milhouse-movement-updates-processor.yml):function}

resources:
  Resources:
    IviaDynamoTable: ${file(config/dynamoDB/Ivia.yaml):IviaDynamoTable}
    IviaResponseDynamoTable: ${file(config/dynamoDB/iviaResponse.yaml):IviaResponseDynamoTable}
    
    # ssm parameter
    IviaResponseDynamoTableStreamArn: ${file(config/ssm/iviaResDdbStreamArnSsm.yml):IviaResponseDynamoTableStreamArn}