IviaResponseDynamoTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: omni-rt-ivia-response-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: "id"
        AttributeType: "S"
    KeySchema:
      - AttributeName: "id"
        KeyType: HASH
