IviaDynamoTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: omni-rt-ivia-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: "id"
        AttributeType: "S"
      - AttributeName: "Housebill"
        AttributeType: "S"
    KeySchema:
      - AttributeName: "id"
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: omni-ivia-houseBill-index-${self:provider.stage}
        KeySchema:
          - AttributeName: "Housebill"
            KeyType: "HASH"
        Projection:
          ProjectionType: "ALL"
    StreamSpecification:
      StreamViewType: NEW_AND_OLD_IMAGES
