IviaResponseDynamoTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: omni-rt-ivia-response-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: "id"
        AttributeType: "S"
      - AttributeName: "ConsolNo"
        AttributeType: "S"
    KeySchema:
      - AttributeName: "id"
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: omni-ivia-ConsolNo-index
        KeySchema:
          - AttributeName: "ConsolNo"
            KeyType: "HASH"
        Projection:
          ProjectionType: "ALL"
    StreamSpecification:
      StreamViewType: NEW_AND_OLD_IMAGES


IviaResponseDynamoTableStreamArn:
  Type: AWS::SSM::Parameter
  Properties:
    Name: /omni-ivia/${self:provider.stage}/iviaResponse/ddb.streamArn
    Type: String
    Value:
      Fn::GetAtt:
        - IviaResponseDynamoTable
        - StreamArn
