IviaDynamoTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: omni-rt-ivia-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: "carrierId"
        AttributeType: "S"
    KeySchema:
      - AttributeName: "carrierId"
        KeyType: HASH
    StreamSpecification:
      StreamViewType: NEW_AND_OLD_IMAGES
