---
function:
  name: omni-ivia-bol-api-${self:provider.stage}
  handler: src/v2/bol-api.handler
  layers:
    - { Ref: OmniIviaLayerLambdaLayer }
  package:
    include:
      - "src/v2/bol-api.js"
      - "src/shared/**"
    exclude:
      - "**/*"
  events:
    - stream: ${ssm:/omni-ivia/${self:provider.stage}/iviaResponse/ddb.streamArn}
  environment:
    GET_DOCUMENT_API: ${ssm:/omni-dw/${self:provider.stage}/websli/api/url}
    BOL_API: ${ssm:/omni-ivia/${self:provider.stage}/bol-api/url}
    BOL_API_AUTH_TOKEN: ${ssm:/omni-ivia/${self:provider.stage}/bol-api/authorization/token~true}
    ADD_DOCUMENT_LOGS_TABLE: ${ssm:/omni-dw/${self:provider.stage}/addDocumentLog/table~true}
    SHIPMENT_HEADER_INDEX: ${ssm:/omni-dw/dev/shipment-header-index/ddb.tableIndex}
    SHIPMENT_HEADER_TABLE: ${ssm:/omni-dw/dev/shipment-header/ddb.tableName}