---
function:
  name: omni-ivia-create-shipment-${self:provider.stage}
  handler: src/create-shipment.handler
  # provisionedConcurrency: 1
  # concurrencyAutoscaling: true
  layers:
    - { Ref: OmniIviaLayerLambdaLayer }
  package:
    include:
      - "src/create-shipment.js"
      - "src/shared/**"
    exclude:
      - "**/*"
  events:
    - stream: arn:aws:dynamodb:us-east-1:332281781429:table/omni-rt-ivia-dev/stream/2022-12-06T16:56:52.308
  environment:
    # DYNAMO_DB_TABLE: ${ssm:/omni-rt-toyota/${self:provider.stage}/apar-failure/ddb.tableName~true}
