---
function:
  name: omni-ivia-create-shipment-${self:provider.stage}
  handler: src/create-shipment.handler
  provisionedConcurrency: 5
  concurrencyAutoscaling: true
  layers:
    - { Ref: OmniIviaLayerLambdaLayer }
  package:
    include:
      - "src/create-shipment.js"
      - "src/shared/**"
    exclude:
      - "**/*"
  events:
    - stream: arn:aws:dynamodb:us-east-1:332281781429:table/omni-rt-ivia-dev/stream/2022-12-06T19:05:20.641
  environment:
    IVIA_CREATE_SHIPMENT_URL: ${ssm:/omni-ivia/${self:provider.stage}/createShipment/url}
    IVIA_CREATE_SHIPMENT_TOKEN: ${ssm:/omni-ivia/${self:provider.stage}/createShipment/token}
    IVIA_XML_UPDATE_URL: ${ssm:/omni-ivia/${self:provider.stage}/createShipment/xmlUpdate/url}
    IVIA_XML_API_USER_ID: ${ssm:/omni-ivia/${self:provider.stage}/createShipment/xmlUpdate/userId}
    IVIA_XML_API_PASS: ${ssm:/omni-ivia/${self:provider.stage}/createShipment/xmlUpdate/password}
    IVIA_RESPONSE_DDB: ${ssm:/omni-rt-toyota/${self:provider.stage}/iviaResponse/ddb.tableName}
